class ForumReplacementService < Service
  # Cool replacements we could eventually do not for pranking
  # [roll N] = random number between 1 and N
  # [roll N, M] = random number between N and M

  WORD_REPLACEMENTS = {
    'actor'             => 'pretenderbloke',
    'actors'            => 'pretenderblokes',
    'alien'             => 'extraterrestrial bopper',
    'aliens'            => 'extraterrestrial boppers',
    'andrew'            => 'andrew (Our Supreme Lord and Overseer)',
    'askew'             => 'cattywampus',
    'attorney'          => 'lawyerboi-at-law',
    'attornies'         => 'lawyerbois-at-law',
    'aware'             => 'cognizant',
    'awesome'           => "bee's knees",
    'bad'               => 'bodge',
    'ball'              => 'blimpy bounce bounce',
    'balls'             => 'blimpy bounce bounces',
    'beanie'            => 'floppy headcover',
    'beanies'           => 'floppy headcovers',
    'bed'               => 'nighttime dreamvessel',
    'beds'              => 'nighttime dreamvessels',
    'bread'             => 'bumberhooten flourknuckles',
    'candy'             => 'chocolate globbernaughts',
    'cane'              => 'boppinstick',
    'canes'             => 'boppinsticks',
    'car'               => 'motorized rollingham',
    'cars'              => 'motorized rollinghams',
    'cat'               => 'feline whiskerdoodle',
    'cats'              => 'feline whiskerdoodles',
    'cereal'            => 'pip pip gollywock',
    'chat'              => 'chitterchatter',
    'chats'             => 'chitterchatters',
    'cheeseburger'      => 'beef wellington ensemble with cheese',
    'cheeseburgers'     => 'beef wellington ensembles with cheese',
    'clock'             => 'Small Ben',
    'clocks'            => 'Small Bens',
    'clown'             => 'loony chuckle fairy',
    'clowns'            => 'loony chuckle fairies',
    'coffee'            => 'bean soup',
    'Coke'              => 'Pepsi',
    'computer'          => 'electrical miraclebox',
    'computers'         => 'electrical miracleboxes',
    'confuse'           => 'bumfuzzle',
    'cookie'            => 'choco chip bicky wicky',
    'cookies'           => 'choco chip bicky wickies',
    'counterclockwise'  => 'widdershin',
    'cumberbatch'       => 'Cramplescrunch',
    'dog'               => 'woofy wolfscendent',
    'dogs'              => 'woofy wolfscendents',
    'door'              => 'wobbly flip-shutter',
    'doors'             => 'wobbly flip-shutters',
    'doorbell'          => 'chimey pushknob',
    'doorbells'         => 'chimey pushknobs',
    'doorknob'          => 'twisting plankhandle',
    'doorknobs'         => 'twisting plankhandles',
    'escalator'         => 'upsy stairsy',
    'exhausted'         => 'wabbit knackered',
    'fake news'         => 'malarkey',
    'family'            => 'mandatory surname-sharers unit',
    'fight'             => 'rumble donnybrook',
    'firework'          => 'merry fizzlebomb',
    'fireworks'         => 'merry fizzlebombs',
    'fish'              => 'aquatic blooper',
    'fishes'            => 'aquatic bloopers',
    'forums'            => 'words warehouse',
    'funny'             => 'laffy taffy',
    'grass'             => 'groundfuzzy',
    'gravy'             => 'meat water',
    'gun'               => 'rooty tooty point-n-shooty',
    'guns'              => 'rooty tooty point-n-shooties',
    'hamburger'         => 'beef wellington ensemble with lettuce',
    'hamburgers'        => 'beef wellington ensembles with lettuce',
    'homework'          => 'timey wimey studystruggles',
    'jelly'             => 'fruit spleggings',
    'Keanu Reeves'      => 'The Chosen One',
    'keyboard'          => 'hoighty toighty tippy typer',
    'keyboards'         => 'hoighty toighty tippy typers',
    'kidnap'            => 'surprise adoption',
    'knife'             => 'stabby stick',
    'knives'            => 'stabby sticks',
    'laptop'            => 'electrotablet with keys',
    'lightbulb'         => 'ceiling-bright',
    'lightbulbs'        => 'ceiling-brights',
    'lock'              => 'lumberlatch',
    'locks'             => 'lumberlatches',
    'marker'            => 'crockety snapwicket',
    'markers'           => 'crockety snapwickets',
    'mistake'           => 'waggly gaff',
    'mistakes'          => 'waggly gaffs',
    'movie'             => 'magical moving picture',
    'movies'            => 'magical moving pictures',
    'netflix and chill' => 'hulu and vibe',
    'nugget'            => "lil' nuggy",
    'nuggets'           => "lil' nuggies",
    'party'             => "poppin' brouhaha",
    'parties'           => "poppin' brouhahas",
    'peanut butter'     => 'nutty-gum',
    'pen'               => 'whimsy flimsy mark and scribbler',
    'pens'              => 'whimsy flimsy mark and scribblers',
    'pepsi'             => 'Coke',
    'podcast'           => 'audiobobbles recording',
    'politician'        => 'public snollygoster',
    'politicians'       => 'public snollygosters',
    'poop'              => 'niffy loo pudding',
    'popsicle'          => 'cold on the cob',
    'road'              => 'cobble-stone-clippity-clop',
    'roads'             => 'cobble-stone-clippity-clops',
    'sandwich'          => 'breaddystack',
    'sandwiches'        => 'breaddystacks',
    'school'            => 'the setting for my coming-of-age story',
    'sheep'             => 'fluffy bumpkinboo',
    'shoe'              => 'leather winklepicker',
    'shoes'             => 'leather winklepickers',
    'skiing'            => 'slippery snownoodle moving',
    'stolen'            => 'nick wicketed',
    'sex'               => 'yiffy wiffy',
    'sick'              => 'collywobble icky',
    'skydiving'         => 'falling out of the sky',
    'smartwatch'        => 'cuff-link time Johnny',
    'smol'              => '<span style="font-size: 5px">smol</span>',
    'snake'             => 'slippery dippery long mover',
    'snakes'            => 'slippery dippery long movers',
    'sock'              => 'soft foot hugger',
    'socks'             => 'soft foot huggers',
    'stairs'            => 'broken escalator',
    'sticky'            => 'icky wicky',
    'success'           => 'Yahtzee!',
    'sup'               => 'soup',
    'sweater'           => 'sheepity sleepity',
    'sweaters'          => 'sheepity sleepities',
    'tiger'             => 'thundercat',
    'tigers'            => 'thundercats',
    'tree'              => 'giant broccoli',
    'trees'             => 'giant broccolis',
    'trick'             => 'bamboozle',
    'tricked'           => 'bamboozled',
    'toe'               => 'foot finger',
    'toes'              => 'foot fingers',
    'toilet'            => 'porcelain poopshooter',
    'toy'               => 'bippity boppity',
    'tooth'             => 'mouth bone',
    'two weeks'         => 'a fortnight',
    'umbrella'          => 'bumbershoot',
    'uwu'               => '(｡◕‿‿◕｡)',
    'wasp'              => 'flying stingywingy',
    'wasps'             => 'flying stingywingies',
    'watch out'         => 'gardyloo',
    'weed'              => "devil's lettuce",
    'whale'             => 'blubberbutt watermutt',
    'whales'            => 'blubberbutt watermutts',
    'wheeze'            => 'sneeze',
    'wire'              => 'electro-rope',
    'wires'             => 'electro-ropes',
    'yuge'              => '<span style="font-size: 20px">yuge</span>'
  }

  def self.replace(text)
    replaced_text = text.dup

    WORD_REPLACEMENTS.each do |trigger, replacement|
      replaced_text.gsub!(/\b#{trigger}\b/i, wrapped(replacement, trigger))
    end
    
    replaced_text.html_safe
  end

  def self.wrapped(text, tooltip)
    "<span class='blue lighten-5 tooltipped' style='padding: 4px' data-tooltip='#{tooltip}'>#{text}</span>"
  end
end