version: "3.8"
services:
  notebookai:
    build: .
    ports:
      - "3000:3000/tcp"
    command: sh -c "rake db:migrate && rm -f tmp/pids/server.pid && exec rails server -b 0.0.0.0"
    volumes:
      - "./:/notebook-ai"
