class AddColumnMigrationFlagToAllContentModels < ActiveRecord::Migration[6.0]
  def change
    add_column(:universes, :columns_migrated_from_old_style, :boolean)
    add_column(:characters, :columns_migrated_from_old_style, :boolean)
    add_column(:locations, :columns_migrated_from_old_style, :boolean)
    add_column(:items, :columns_migrated_from_old_style, :boolean)
    add_column(:buildings, :columns_migrated_from_old_style, :boolean)
    add_column(:conditions, :columns_migrated_from_old_style, :boolean)
    add_column(:continents, :columns_migrated_from_old_style, :boolean)
    add_column(:countries, :columns_migrated_from_old_style, :boolean)
    add_column(:creatures, :columns_migrated_from_old_style, :boolean)
    add_column(:deities, :columns_migrated_from_old_style, :boolean)
    add_column(:floras, :columns_migrated_from_old_style, :boolean)
    add_column(:foods, :columns_migrated_from_old_style, :boolean)
    add_column(:governments, :columns_migrated_from_old_style, :boolean)
    add_column(:groups, :columns_migrated_from_old_style, :boolean)
    add_column(:jobs, :columns_migrated_from_old_style, :boolean)
    add_column(:landmarks, :columns_migrated_from_old_style, :boolean)
    add_column(:languages, :columns_migrated_from_old_style, :boolean)
    add_column(:magics, :columns_migrated_from_old_style, :boolean)
    add_column(:planets, :columns_migrated_from_old_style, :boolean)
    add_column(:races, :columns_migrated_from_old_style, :boolean)
    add_column(:religions, :columns_migrated_from_old_style, :boolean)
    add_column(:scenes, :columns_migrated_from_old_style, :boolean)
    add_column(:schools, :columns_migrated_from_old_style, :boolean)
    add_column(:sports, :columns_migrated_from_old_style, :boolean)
    add_column(:technologies, :columns_migrated_from_old_style, :boolean)
    add_column(:towns, :columns_migrated_from_old_style, :boolean)
    add_column(:traditions, :columns_migrated_from_old_style, :boolean)
    add_column(:vehicles, :columns_migrated_from_old_style, :boolean)

    change_column_default(:universes, :columns_migrated_from_old_style, {:from=>nil, :to=>true})
    change_column_default(:characters, :columns_migrated_from_old_style, {:from=>nil, :to=>true})
    change_column_default(:locations, :columns_migrated_from_old_style, {:from=>nil, :to=>true})
    change_column_default(:items, :columns_migrated_from_old_style, {:from=>nil, :to=>true})
    change_column_default(:buildings, :columns_migrated_from_old_style, {:from=>nil, :to=>true})
    change_column_default(:conditions, :columns_migrated_from_old_style, {:from=>nil, :to=>true})
    change_column_default(:continents, :columns_migrated_from_old_style, {:from=>nil, :to=>true})
    change_column_default(:countries, :columns_migrated_from_old_style, {:from=>nil, :to=>true})
    change_column_default(:creatures, :columns_migrated_from_old_style, {:from=>nil, :to=>true})
    change_column_default(:deities, :columns_migrated_from_old_style, {:from=>nil, :to=>true})
    change_column_default(:floras, :columns_migrated_from_old_style, {:from=>nil, :to=>true})
    change_column_default(:foods, :columns_migrated_from_old_style, {:from=>nil, :to=>true})
    change_column_default(:governments, :columns_migrated_from_old_style, {:from=>nil, :to=>true})
    change_column_default(:groups, :columns_migrated_from_old_style, {:from=>nil, :to=>true})
    change_column_default(:jobs, :columns_migrated_from_old_style, {:from=>nil, :to=>true})
    change_column_default(:landmarks, :columns_migrated_from_old_style, {:from=>nil, :to=>true})
    change_column_default(:languages, :columns_migrated_from_old_style, {:from=>nil, :to=>true})
    change_column_default(:magics, :columns_migrated_from_old_style, {:from=>nil, :to=>true})
    change_column_default(:planets, :columns_migrated_from_old_style, {:from=>nil, :to=>true})
    change_column_default(:races, :columns_migrated_from_old_style, {:from=>nil, :to=>true})
    change_column_default(:religions, :columns_migrated_from_old_style, {:from=>nil, :to=>true})
    change_column_default(:scenes, :columns_migrated_from_old_style, {:from=>nil, :to=>true})
    change_column_default(:schools, :columns_migrated_from_old_style, {:from=>nil, :to=>true})
    change_column_default(:sports, :columns_migrated_from_old_style, {:from=>nil, :to=>true})
    change_column_default(:technologies, :columns_migrated_from_old_style, {:from=>nil, :to=>true})
    change_column_default(:towns, :columns_migrated_from_old_style, {:from=>nil, :to=>true})
    change_column_default(:traditions, :columns_migrated_from_old_style, {:from=>nil, :to=>true})
    change_column_default(:vehicles, :columns_migrated_from_old_style, {:from=>nil, :to=>true})

  end
end
